apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oraiscan-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:oraichain/oraiscan-frontend.git
    targetRevision: HEAD
    path: k8s/prod
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
