apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oraiscan-frontend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: staging.oraiscan.io
    http:
      paths:
      - path: /
        backend:
          serviceName: oraiscan-frontend
          servicePort: 5000
  - host: staging-scan.orai.io
    http:
      paths:
      - path: /
        backend:
          serviceName: oraiscan-frontend
          servicePort: 5000